# Generated by Django 5.1.2 on 2025-03-26 21:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('ip', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrarColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('empresa', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrarUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Perifericos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('modelo', models.CharField(max_length=60)),
                ('numero_serie', models.CharField(max_length=60)),
                ('fecha_adquisicion', models.DateField()),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.registrarcolaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.registrarcolaborador')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrarEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(default='sin memoria', max_length=50)),
                ('memoria', models.CharField(default='sin memoria', max_length=50)),
                ('procesador', models.CharField(default='sin procesador', max_length=50)),
                ('office', models.CharField(max_length=60)),
                ('serial', models.CharField(max_length=60, unique=True)),
                ('sistema_operativo', models.CharField(max_length=60)),
                ('fecha_adquisicion', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='equipos/')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.registrarcolaborador')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrarLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(default='sin memoria', max_length=60)),
                ('contrasena', models.CharField(max_length=60)),
                ('serial_office', models.CharField(default='sin serial', max_length=60)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.registrarcolaborador')),
            ],
        ),
    ]
