# Generated by Django 5.1.2 on 2025-03-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrarusuario',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
