# Generated by Django 5.1.2 on 2024-11-03 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrarlicencia',
            old_name='contraseña',
            new_name='contrasena',
        ),
    ]
