# Generated by Django 5.1.2 on 2025-04-02 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_registrarusuario_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='MantenimientoImpresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('realizado_por', models.CharField(blank=True, max_length=100)),
                ('impresora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='aplicacion.impresora')),
            ],
        ),
    ]
