# Generated by Django 5.1.2 on 2024-11-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_rename_contraseña_registrarlicencia_contrasena'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrarequipo',
            old_name='modelo',
            new_name='sistema_operativo',
        ),
        migrations.RemoveField(
            model_name='registrarequipo',
            name='memoria',
        ),
        migrations.RemoveField(
            model_name='registrarequipo',
            name='procesador',
        ),
        migrations.RemoveField(
            model_name='registrarequipo',
            name='serial_office',
        ),
        migrations.RemoveField(
            model_name='registrarequipo',
            name='vida_util',
        ),
        migrations.AlterField(
            model_name='registrarequipo',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='equipos/'),
        ),
        migrations.AlterField(
            model_name='registrarequipo',
            name='fecha_adquisicion',
            field=models.CharField(max_length=50),
        ),
    ]
