# Generated by Django 5.1.2 on 2025-04-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_mantenimientoimpresora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impresora',
            old_name='ip',
            new_name='direccion_ip',
        ),
    ]
