# Generated by Django 5.1.2 on 2024-11-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_rename_modelo_registrarequipo_sistema_operativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrarequipo',
            name='memoria',
            field=models.CharField(default='sin memoria', max_length=50),
        ),
        migrations.AddField(
            model_name='registrarequipo',
            name='procesador',
            field=models.CharField(default='sin procesador', max_length=50),
        ),
        migrations.AddField(
            model_name='registrarequipo',
            name='serial_office',
            field=models.CharField(default='sin serial', max_length=60),
        ),
    ]
