# Generated by Django 5.1.2 on 2024-12-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_registrarequipo_memoria_registrarequipo_procesador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Impresora',
            fields=[
                ('id_impre', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('ip', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='equipo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
    ]
