# Generated by Django 5.1.2 on 2024-12-16 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_area_impresora_alter_mantenimiento_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='registrarequipo',
            name='serial_office',
        ),
        migrations.RemoveField(
            model_name='registrarlicencia',
            name='nombre',
        ),
        migrations.AddField(
            model_name='registrarequipo',
            name='modelo',
            field=models.CharField(default='sin memoria', max_length=50),
        ),
        migrations.AddField(
            model_name='registrarequipo',
            name='windows',
            field=models.CharField(default='sin memoria', max_length=60),
        ),
        migrations.AddField(
            model_name='registrarlicencia',
            name='correo',
            field=models.CharField(default='sin memoria', max_length=60),
        ),
        migrations.AddField(
            model_name='registrarlicencia',
            name='serial_office',
            field=models.CharField(default='sin serial', max_length=60),
        ),
        migrations.AlterField(
            model_name='registrarequipo',
            name='serial',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_ip', models.CharField(max_length=15)),
                ('descripcion', models.TextField()),
                ('nodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switches', to='aplicacion.nodo')),
            ],
        ),
        migrations.CreateModel(
            name='Conexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_conexion', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('nodo_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='aplicacion.nodo')),
                ('nodo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='aplicacion.nodo')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.switch')),
            ],
        ),
    ]
