# Generated by Django 5.1.2 on 2025-01-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_nodo_remove_registrarequipo_serial_office_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='registrarequipo',
            name='windows',
        ),
    ]
