# Generated by Django 5.1.2 on 2025-01-03 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_custom_remove_registrarequipo_windows'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrarColaborador',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('empresa', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('licencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.registrarlicencia')),
            ],
        ),
        migrations.DeleteModel(
            name='Custom',
        ),
        migrations.RenameField(
            model_name='registrarusuario',
            old_name='area',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='registrarusuario',
            old_name='cargo',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='registrarusuario',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='registrarusuario',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='registrarusuario',
            name='licencia',
        ),
        migrations.RemoveField(
            model_name='registrarusuario',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='registrarequipo',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.registrarcolaborador'),
        ),
    ]
