# Generated by Django 5.1.2 on 2025-01-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_alter_registrarusuario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrarusuario',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
