# Generated by Django 5.1.2 on 2025-01-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0011_alter_registrarusuario_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrarcolaborador',
            old_name='id_usuario',
            new_name='id_colaborador',
        ),
    ]
