# Generated by Django 5.1.2 on 2025-03-17 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0012_rename_id_usuario_registrarcolaborador_id_colaborador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perifericos',
            fields=[
                ('id_peri', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('modelo', models.CharField(max_length=60)),
                ('numero_serie', models.CharField(max_length=60)),
                ('fecha_adquisicion', models.CharField(max_length=50)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.registrarcolaborador')),
            ],
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='nodo',
        ),
        migrations.DeleteModel(
            name='Conexion',
        ),
        migrations.DeleteModel(
            name='Nodo',
        ),
        migrations.DeleteModel(
            name='Switch',
        ),
    ]
