# Generated by Django 5.1.2 on 2025-03-17 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0013_perifericos_delete_area_remove_switch_nodo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrarMapa',
        ),
    ]
